name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
            
            -   name: Set up Python
                uses: actions/setup-python@v5
                with:
                    python-version: '3.12'
            
            -   name: Install dependencies
                run: |
                    echo   "skip > python -m pip install --upgrade pip"
                    pip install -r requirements.txt  --use-pep517
                    make install
            
            -   name: Set PYTHONPATH
                run: |
                    export PYTHONPATH=$(pwd)
                    echo "PYTHONPATH set to $(pwd)"
                    ls -la $(pwd)
            
            -   name: Run tests
                env:
                    PYTEST_ADDOPTS: "--setup-show --confcutdir=."
                run: |
                    make test
                  